<?php

// AQUI ONDE PAREI O CRUD DO TUTOR E DO VETERINARIO ESTÃO FUNCIONANDO PERFEITAMENTE
// AGORA PRECISO FAZER O LOGIN DO TUTOR E DO VETERINARIO E AUTENTICAR NAS PAGINAS RESTRITAS
// MAS ANTES PRECISO ENVIAR OS DADOS DO FORMULARIO VIA POST
// O LOGIN SERA FEITO VIA POST E A AUTENTICAÇÃO SERA FEITA VIA SESSION
// A AUTENTICAÇÃO SERA FEITA NO ARQUIVO php/autentica.php
// lOGIN SERÁ NUMA PÁGINA SEPARADA php/login-tutor.php E php/login-veterinario.php

// FALTA ISSO DE AUTENTICAR O LOGIN E FAZER A PAGINA RESTRITA
// E FAZER VALIDAÇÃO NO FORMULARIO DE CADASTRO DE TUTOR E VETERINARIO
// E FAZER VALIDAÇÃO NO FORMULARIO DE LOGIN DE TUTOR E VETERINARIO

// APOS ISSO POSSO GRAVAR O VÍDEO (DOMINGO) E ENVIAR O LINK PARA O PROFESSOR